spring:

  #h2:
  # console:
  #   enabled: true

  datasource:
    url: jdbc:oracle:thin:@jel_high?TNS_ADMIN=/Users/ijieun/02Workspaces/02SQL/New/Wallet_jel
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username: jel
    password: xxxxxxAt22cc

  jpa:
    database-platform: org.hibernate.dialect.Oracle10gDialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true
logging:
  level:
    me.silvernine: DEBUG

jwt:
  header: Authorization
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400