spring:
  datasource:
    url: jdbc:oracle:thin:@jel_high?TNS_ADMIN=/Users/ijieun/02Workspaces/02SQL/New/Wallet_jel
    username: jel
    password: xxxxxxAt22cc
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: oracle
    properties:
      hibernate:
        format_sql: true


    database-platform: org.hibernate.dialect.Oracle12cDialect

logging:
  level:
    jpa: DEBUG